# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Melvin Perera
tagline:          'Ramblings and Thoughts'
description:      'A collection of data science projects that I have done, interspersed with ramblings, thoughts and a couple of jokes' 
url:              http://hyde.getpoole.com
#baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/melvinperera

plugins: [jekyll-paginate,jekyll-gist]
